apiVersion: kai.alibabacloud.com/v1alpha1
kind: TrainingJob
metadata:
  annotations:
    arena.kubeflow.org/username: kubecfg:certauth:admin
    job-supervisor.kube-ai.io/job-start-time: "1677143995"
    job-supervisor.kube-ai.io/max-wait-time: "3000"
    job-supervisor.kube-ai.io/spot-instance: "true"
    requestGPUsOfJobOwner: "3"
  creationTimestamp: "2023-02-23T09:19:55Z"
  generation: 2
  labels:
    app: etjob
    arena.kubeflow.org/uid: 3399d840e8b371ed7ca45dda29debeb1
    chart: etjob-0.3.0
    createdBy: ETJob
    heritage: Helm
    job_name: imagenet-resnet50-normal-spot-777
    release: imagenet-resnet50-normal-spot-777
  name: imagenet-resnet50-normal-spot-777
  namespace: default-group
  resourceVersion: "2333526"
  uid: beddab6d-f5c5-4537-adad-28e69d9a8331
spec:
  backoffLimit: 6
  cleanPodPolicy: Running
  etReplicaSpecs:
    launcher:
      replicas: 1
      template:
        metadata:
          annotations:
            arena.kubeflow.org/username: kubecfg:certauth:admin
            job-supervisor.kube-ai.io/max-wait-time: "3000"
            job-supervisor.kube-ai.io/spot-instance: "true"
            requestGPUsOfJobOwner: "3"
          labels:
            app: etjob
            arena.kubeflow.org/uid: 3399d840e8b371ed7ca45dda29debeb1
            chart: etjob-0.3.0
            createdBy: ETJob
            heritage: Helm
            job_name: imagenet-resnet50-normal-spot-777
            master-pod-name: imagenet-resnet50-normal-spot-777-launcher
            release: imagenet-resnet50-normal-spot-777
          name: imagenet-resnet50-normal-spot-777
        spec:
          containers:
          - command:
            - sh
            - -c
            - horovodrun --log-level DEBUG --verbose -np $((${workers}*${gpus})) --min-np
              $((${minWorkers}*${gpus})) --max-np $((${maxWorkers}*${gpus})) --host-discovery-script
              /etc/edl/discover_hosts.sh python /mnt/example/imagenet/pytorch_imagenet_resnet50_elastic.py  --epochs=100
              --num-workers=6 --train-dir=/mnt/data/imageNet/ILSVRC/Data/CLS-LOC-MINI/train
              --val-dir=/mnt/data/imageNet/ILSVRC/Data/CLS-LOC-MINI/val --checkpoint-format=./imagenet-resnet50-normal-spot-777-checkpoint-{epoch}.pth.tar
              --name=imagenet-resnet50-normal-spot-777
            env:
            - name: gpus
              value: "1"
            - name: maxWorkers
              value: "128"
            - name: minWorkers
              value: "1"
            - name: workers
              value: "3"
            image: ai-studio-registry.cn-beijing.cr.aliyuncs.com/kube-ai/horovod:0.26
            imagePullPolicy: Always
            name: et
            resources:
              limits:
                cpu: "3"
                memory: 25Gi
              requests:
                cpu: "3"
                memory: 25Gi
            volumeMounts:
            - mountPath: /mnt
              name: imagenet-pvc
            - mountPath: /dev/shm
              name: dshm
            workingDir: /mnt
          nodeSelector:
            instance_type: spot-launcher
          volumes:
          - name: imagenet-pvc
            persistentVolumeClaim:
              claimName: imagenet-pvc
          - emptyDir:
              medium: Memory
              sizeLimit: 2Gi
            name: dshm
    worker:
      maxReplicas: 128
      minReplicas: 1
      replicas: 3
      restartPolicy: Always
      template:
        metadata:
          annotations:
            arena.kubeflow.org/username: kubecfg:certauth:admin
            job-supervisor.kube-ai.io/max-wait-time: "3000"
            job-supervisor.kube-ai.io/spot-instance: "true"
            requestGPUsOfJobOwner: "3"
          labels:
            app: etjob
            arena.kubeflow.org/uid: 3399d840e8b371ed7ca45dda29debeb1
            chart: etjob-0.3.0
            createdBy: ETJob
            heritage: Helm
            job_name: imagenet-resnet50-normal-spot-777
            release: imagenet-resnet50-normal-spot-777
          name: imagenet-resnet50-normal-spot-777
        spec:
          containers:
          - env:
            - name: gpus
              value: "1"
            - name: maxWorkers
              value: "128"
            - name: minWorkers
              value: "1"
            - name: workers
              value: "3"
            image: ai-studio-registry.cn-beijing.cr.aliyuncs.com/kube-ai/horovod:0.26
            imagePullPolicy: Always
            name: et
            resources:
              limits:
                cpu: "3"
                memory: 25Gi
                nvidia.com/gpu: "1"
              requests:
                cpu: "3"
                memory: 25Gi
                nvidia.com/gpu: "1"
            volumeMounts:
            - mountPath: /mnt
              name: imagenet-pvc
            - mountPath: /dev/shm
              name: dshm
            workingDir: /mnt
          nodeSelector:
            instance_type: spot
          volumes:
          - name: imagenet-pvc
            persistentVolumeClaim:
              claimName: imagenet-pvc
          - emptyDir:
              medium: Memory
              sizeLimit: 2Gi
            name: dshm
  restartPolicy: Never
status:
  conditions:
  - lastTransitionTime: "2023-02-23T09:19:55Z"
    lastUpdateTime: "2023-02-23T09:19:55Z"
    message: TrainingJob imagenet-resnet50-normal-spot-777 is created.
    reason: TrainingJobCreated
    status: "True"
    type: Created
  - lastTransitionTime: "2023-02-23T09:19:55Z"
    lastUpdateTime: "2023-02-23T09:19:55Z"
    message: create trainingjob(default-group/imagenet-resnet50-normal-spot-777) workers
    status: "True"
    type: WorkersCreated
  phase: Created
  replicaStatuses:
    Launcher: {}
    Worker: {}
  restartCount: 0
  startTime: "2023-02-23T09:19:55Z"
  targetWorkers:
  - imagenet-resnet50-normal-spot-777-worker-0
  - imagenet-resnet50-normal-spot-777-worker-1
  - imagenet-resnet50-normal-spot-777-worker-2
