apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: default-group
spec:
  containers:
  - name: container1
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    image: busybox:1.28
    command: [ "sh", "-c", "while [ true ]; do echo 'Hello'; sleep 10; done | tee -a /logs/hello.txt" ]
    volumeMounts:
    - name: workdir1
      mountPath: /logs
      # The variable expansion uses round brackets (not curly brackets).
      subPathExpr: $(POD_NAME)
  restartPolicy: Never
  volumes:
  - name: workdir1
    persistentVolumeClaim:
      claimName: tfserve-oss-pvc    

---
apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: default-group
spec:
  containers:
  - name: container1
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    image: busybox:1.28
    #command: [ "sh", "-c", "while [ true ]; do echo 'Hello'; sleep 10; done | tee -a /logs/$(POD_NAME)/hello.txt" ]
    args:
    - --log=/logs/$(SOUL_TENANT)/$(SOUL_APPNAME)/$(POD_IP)/$(POD_ID)
    volumeMounts:
    - name: workdir1
      mountPath: /logs
     # subPathExpr: $(POD_NAME)
  restartPolicy: Never
  volumes:
  - name: workdir1
    persistentVolumeClaim:
      claimName: tfserve-oss-pvc            